### ISSUE TITLE
StandardOutboundRequestHandlerTest failes test

### ISSUE THREAD

**Issue by LukasStrickler** [joscha-st/bad_walden_stadtwerke#104]
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ bad_walden_stadtwerke ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.bad_walden_stadtwerke.controller.language.LanguageControllerTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 s -- in com.bad_walden_stadtwerke.controller.language.LanguageControllerTest
[INFO] Running com.bad_walden_stadtwerke.components.TariffTableDisplayTest
May 02, 2024 12:04:17 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation
2024-05-02 12:04:17.874 java[6764:151894] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
WARNING: A Java agent has been loaded dynamically (/Users/lukasstrickler/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.12/byte-buddy-agent-1.14.12.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.035 s -- in com.bad_walden_stadtwerke.components.TariffTableDisplayTest
[INFO] Running com.bad_walden_stadtwerke.components.errorHandling.ExceptionPopupTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s -- in com.bad_walden_stadtwerke.components.errorHandling.ExceptionPopupTest
[INFO] Running com.bad_walden_stadtwerke.model.types.billingAdress.BillingAddressValidatorTest
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 s -- in com.bad_walden_stadtwerke.model.types.billingAdress.BillingAddressValidatorTest
[INFO] Running com.bad_walden_stadtwerke.model.initialSignUp.SignUpManagerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.159 s -- in com.bad_walden_stadtwerke.model.initialSignUp.SignUpManagerTest
[INFO] Running com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandlerTest
Communication: New client initialized
Communication: StandardPostOutboundRequest prepared: https://request-handling.int.bad-walden-stadtwerke.com/user-data/billing-address POST
Communication: response code: 200
Communication: StandardGetOutboundRequest prepared: https://request-handling.int.bad-walden-stadtwerke.com/test GET
Communication: response code: 200
Communication: StandardGetOutboundRequest prepared: https://request-handling.int.bad-walden-stadtwerke.com/tariff-data/electricity GET
Communication: response code: 200
Communication: StandardPostOutboundRequest prepared: https://request-handling.int.bad-walden-stadtwerke.com/user-data/tariff-selection POST
Communication: response code: 503
Communication: Error: 503 - Entschuldigung, der Service ist derzeit nicht verfügbar. Bitte versuchen Sie es später erneut.
Communication: StandardPostOutboundRequest prepared: https://request-handling.int.bad-walden-stadtwerke.com/test POST
Communication: response code: 200
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.102 s <<< FAILURE! -- in com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandlerTest
[ERROR] com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandlerTest.whenTariffSelectionForUserOutboundRequest_thenTrueIsReturned -- Time elapsed: 0.014 s <<< ERROR!
java.lang.IllegalStateException: Not on FX application thread; currentThread = main
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:297)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:458)
	at javafx.graphics/javafx.stage.Stage.<init>(Stage.java:258)
	at javafx.graphics/javafx.stage.Stage.<init>(Stage.java:244)
	at javafx.controls/javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
	at javafx.controls/javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
	at javafx.controls/javafx.scene.control.Dialog.<init>(Dialog.java:268)
	at javafx.controls/javafx.scene.control.Alert.<init>(Alert.java:247)
	at javafx.controls/javafx.scene.control.Alert.<init>(Alert.java:222)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.components.errorHandling.ExceptionPopup.showErrorPopup(ExceptionPopup.java:9)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandler.displayNetworkError(StandardOutboundRequestHandler.java:107)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandler.sendRequestToServer(StandardOutboundRequestHandler.java:87)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandler.makeStandardPostOutboundRequest(StandardOutboundRequestHandler.java:32)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandler.makeTariffSelectionForUserOutboundRequest(StandardOutboundRequestHandler.java:70)
	at com.bad_walden_stadtwerke@1.0-SNAPSHOT/com.bad_walden_stadtwerke.model.communication.StandardOutboundRequestHandlerTest.whenTariffSelectionForUserOutboundRequest_thenTrueIsReturned(StandardOutboundRequestHandlerTest.java:48)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   StandardOutboundRequestHandlerTest.whenTariffSelectionForUserOutboundRequest_thenTrueIsReturned:48 » IllegalState Not on FX application thread; currentThread = main
[INFO] 
[ERROR] Tests run: 60, Failures: 0, Errors: 1, Skipped: 0
[INFO]

**Comment by joscha-st** [comment]
This is not an actual failure, however if variable in mock is set to mock a failure, the test will of course also fail.

**Comment by LukasStrickler** [comment]
pls adjust so all test pass and not fail, adjust the asserted result
